### ISSUE TITLE
small visual incompatibility with ebwizardy wizards

### ISSUE THREAD

**Issue by xemnes** [Fuzss/tradinggui#4]
not a massive issue but its still quite misleading and will make people believe it doesnt work.
when trading with wizards, theres a trade thats always available that allows you to trade in unused spell books for crystals. this accepts all spell books.
with this mod, it looks as though this is broken as when you add a spell book to the offer, the output is empty. however the output slot is just invisible, the trade will go through if you click the empty slot and you will receive the item. 
i looked at the code, it seems ebwizardry uses a special version of the trade system to accept wildcards which i believe may be the issue here.
heres a video showing the problem https://gfycat.com/bewitchedactualindianspinyloach

**Comment by Fuzss** [comment]
I actually looked into this and they manually render this one item into the result slot, which does not work with my custom screen.
I'm not doing 1.12 modding anymore, so there won't be no fix unfortunately, although I don't think the issue is too serious.
